<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Surat_masuk_model extends CI_Model
{

    public $table = 'surat_masuk';
    public $id = 'id_masuk';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_masuk,nomor_surat,perihal,tanggal,pengirim,penerima');
        $this->datatables->from('surat_masuk');
        //add this line for join
        //$this->datatables->join('table2', 'surat_masuk.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('surat_masuk/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('surat_masuk/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('surat_masuk/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_masuk');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_masuk', $q);
	$this->db->or_like('nomor_surat', $q);
	$this->db->or_like('perihal', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('pengirim', $q);
	$this->db->or_like('penerima', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_masuk', $q);
	$this->db->or_like('nomor_surat', $q);
	$this->db->or_like('perihal', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('pengirim', $q);
	$this->db->or_like('penerima', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Surat_masuk_model.php */
/* Location: ./application/models/Surat_masuk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-28 17:43:33 */
/* http://harviacode.com */