<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Surat_keluar_model extends CI_Model
{

    public $table = 'surat_keluar';
    public $id = 'id_keluar';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_keluar,nomor_surat,perihal,tanggal,penerima,pengirim');
        $this->datatables->from('surat_keluar');
        //add this line for join
        //$this->datatables->join('table2', 'surat_keluar.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('surat_keluar/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('surat_keluar/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('surat_keluar/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_keluar');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_keluar', $q);
	$this->db->or_like('nomor_surat', $q);
	$this->db->or_like('perihal', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('penerima', $q);
	$this->db->or_like('pengirim', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_keluar', $q);
	$this->db->or_like('nomor_surat', $q);
	$this->db->or_like('perihal', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('penerima', $q);
	$this->db->or_like('pengirim', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Surat_keluar_model.php */
/* Location: ./application/models/Surat_keluar_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-28 17:43:40 */
/* http://harviacode.com */